name: CI
on:
  push:
  pull_request:
jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: checkout git repository
        uses: actions/checkout@v5

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: install modules
        run: yarn install

      - name: build production project
        run: yarn build
        if: always()

      - name: lint typescript
        run: yarn lint
        if: always()

      - name: check format with prettier
        run: yarn format:check
        if: always()
